### ISSUE TITLE
Send 'Refunded' notices for charged back transaction

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-memberpress#20]
For chargebacks we update the MemberPress transaction status to 'Refunded', but don't send the 'Refunded' notices:

https://github.com/pronamic/wp-pronamic-pay-memberpress/blob/4218e02826ab4ae3249aca3649a425ea5f4c97bd/src/Extension.php#L341-L380

In internal support ticket https://secure.helpscout.net/conversation/2642579484/27460 we received a question about informing site admins about these chargebacks:

> Onlangs hebben we een refund gehad die terug te zien is in Mollie. Ook is deze te zien in de subscription en toen netjes on hold gegaan, dus dat deel van het proces is helemaal goed gegaan. Echter hebben wij in memberpress de optie aanstaan dat onze administratie een melding zou moeten krijgen bij een refund, deze hebben ze echter niet gehad en is ook niet uitgestuurd volgens de mail log die ik bijhoud.
>
> Hoe kunnen we ervoor zorgen dat onze administratie in de toekomst wel een melding krijgt bij refunds? Er zitten namelijk wat handmatige acties aan onze meberships die tijdig gestopt moeten worden in het geval van het terugdraaien van een betaling.

I suggest also sending the notices (lines 376-379) for chargebacks. What do you think, @remcotolsma?

**Comment by remcotolsma** [comment]
Seems fine to me, can there be customer notices and are they also suitable to send in the case of chargebacks?

**Comment by rvdsteege** [comment]
Yes, there are customer and admin notices for refunds:

<img width="730" alt="Scherm­afbeelding 2024-07-05 om 09 48 53" src="https://github.com/pronamic/wp-pronamic-pay-memberpress/assets/10371164/9930707f-a327-44eb-a33d-92b71c341816">

<img width="722" alt="Scherm­afbeelding 2024-07-05 om 09 49 02" src="https://github.com/pronamic/wp-pronamic-pay-memberpress/assets/10371164/219f59c1-60a1-4eed-8e1d-b032fdc84058">
